### ISSUE TITLE
[BUG] cannot graceful stop due to leaked Timeout

### ISSUE THREAD

**Issue by loynoir** [isaacs/ttlcache#15]
### Reproduce
```ts
import TTLCache from "https://esm.sh/@isaacs/ttlcache@1.2.0";

const cache = new TTLCache({
  max: 10000,
  ttl: 1000,
})

cache.set('a', 'b', {ttl: 180000})
cache.clear()
```

### Actual
```sh
$ time deno run reproduce.ts
real    3m
```

### Expected
```sh
$ time deno run reproduce.ts
real    0m
```

### Source
https://github.com/isaacs/ttlcache/blob/7317c571b52cb04a16214261b87f7055d0eff04d/index.js#L78-L83

### Also
nodejs also cannot graceful stop due to that leaked Timeout

**Comment by isaacs** [comment]
Node stops gracefully because of the `t.unref()` call.  It looks like Deno needs an explicit `clearTimeout` to forget about it?
