### ISSUE TITLE
cache expiration does not work

### ISSUE THREAD

**Issue by kkozlik** [isaacs/ttlcache#24]
Although the readme contain this example:

```
const TTLCache = require('@isaacs/ttlcache')
const cache = new TTLCache({ max: 10000, ttl: 1000 })

// set some value
cache.set(1, 2)

// 999 ms later
cache.has(1) // returns true
cache.get(1) // returns 2

// 1000 ms later
cache.get(1) // returns undefined
cache.has(1) // returns false
```

it does not work. The `cache.get(1)` still returning the item and the `cache.has(1)` returns `true` even after the expiration timeout. IMO it even can't work as neither the `get()` nor the `has()` function check the `expirationMap`, they check just the `data` map.

The `getRemainingTTL()` function correctly return `0` when the item expire, but neither call of this function get the item out of the cache.

**Comment by isaacs** [comment]
The item gets purged in a setTimeout created in `setTTL`. Functions scheduled with setTimeout aren't guaranteed to be perfectly timed, since it depends on event loop activity, so it is possible that it'll store the item for slightly longer than the stated ttl, especially if the program is busy on cpu for the whole time. There are tests showing this working.

**Comment by kkozlik** [comment]
Thanks for explanation. I did not noticed the setTimeout function. However in my case there were items loong after the expiration, not few milis as one could expect due to program busy etc... That was minutes and I did not want to wait longer.

Cannot there be some race condition or something like this that cancel the setTimeout? Just guessing, but I think that I have seen items expiring on initial of my program run, but they stopped expire later.. 

Anyway, I have workaround the issue by checking the `getRemainingTTL()` when retrieving items from the cache.

**Comment by isaacs** [comment]
@kkozlik You might try upgrading to v1.3.0.  @marcbachmann's PR makes things quite a bit more efficient, so it'll be considerably closer to real time.

But, if you're for example looping on CPU for 1000ms, or otherwise keeping the system busy, then no, it's not ever going to be able to expire right on the appropriate moment.

It could _fake_ it, like LRUCache does, and delete the item and return undefined when you attempt to retrieve it if it's past its ttl.  But otherwise, it's always going to be a best effort eviction.

**Comment by isaacs** [comment]
Or better yet, yeah, use 1.4.0, and set `checkAgeOnGet: true` in the options.  Then it'll pretend to be real-time, even though setTimeout isn't.

**Comment by isaacs** [comment]
Neat side effect of 1.3 and 1.4... you can do `const cache = new TTLCache({ checkAgeOnGet: true })` and then call `cache.cancelTimer()`, and it'll still appear to do the right thing, even though it's actually holding items forever.  If you also set a `max`, and `updateAgeOnGet`, then it's effectively just a slower node-lrucache with fewer features lol

**Comment by kkozlik** [comment]
> What environment did you use?

NodeJs

> But, if you're for example looping on CPU for 1000ms, or otherwise keeping the system busy, then no, it's not ever going to be able to expire right on the appropriate moment.

Nope. That application is not intensive on CPU usage and the system is not busy at all. Expiration time of my cache is 10s and I need to refresh the values after those 10s (or so, does not have to be too exact). But the `cache.has(...)` returned `true` forever and `cache.get(...)` returned the cached value. It never expired, or maybe after really looong time.

Thanks for the update, I will try the new version...

**Comment by kkozlik** [comment]
Btw. as checking the changes, it seems the `has()` function is not affected by the `checkAgeOnGet` setting, is it?

**Comment by isaacs** [comment]
Has is not. Could add a checkAgeOnHas options as well I guess.

**Comment by ayushjain2809** [comment]
@isaacs I have seen this issue in NodeJS 12 and 14. I believe it has to do with the low precision of  `Date.now()`. `performance.now()` doesn't have this issue. So the following part might wrongly cause purgeStale to return even when there is some key(s) which should ideally expire.  https://github.com/isaacs/ttlcache/blob/716c4d72eb5105a99422edc1e8a180bd1452826d/index.js#L272-L276 
The affected keys will be dropped in the next call to purgeStale, but there could be a "looong" delay before that.
