### ISSUE TITLE
Potential race condition issues

### ISSUE THREAD

**Issue by Tirke** [isaacs/ttlcache#26]
Hello,

I apologize for the brief nature of this issue report. Unfortunately, we have limited information to provide, and we are encountering difficulties in reproducing the issue locally. Our usage of the cache is within the context of a Nest microservice, where we have instantiated the cache four times. Recently, we have started experiencing the following problem:

```
TypeError: this.expirations[exp] is not iterable
    at TTLCache.purgeStale (/app/node_modules/.pnpm/@isaacs+ttlcache@1.4.0/node_modules/@isaacs/ttlcache/index.js:277:40)
    at Timeout._onTimeout (/app/node_modules/.pnpm/@isaacs+ttlcache@1.4.0/node_modules/@isaacs/ttlcache/index.js:71:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

Upon inspecting the source code of the library, it appears that `this.expirations` undergoes significant mutations, which may result in `undefined` key values. However, beyond this observation, we do not have additional insights to contribute. We understand that this may not be the most informative issue for you, but we wanted to report it nonetheless.

Thank you for your attention to this matter.

**Comment by isaacs** [comment]
Hm, this is really mysterious.

The mutations to the `expirations` object are definitely frequent, but they're all either setting with an array as the value and the key being a number or the string `Infinity`, or they delete it from the object.

If it's deleted, then it shouldn't show up in the loop around line 277. If it's set to an array, then it should be iterable.

Is it possible that you're doing something in the disposal method or some other place that might be triggering a `purgeStale` at unexpected times?

In the meantime, I'm happy to add a guard around that, this should prevent the issue, but the mystery will nag me until it's figured out 😅 

```diff
diff --git a/index.js b/index.js
index 1183c10..81ffdad 100644
--- a/index.js
+++ b/index.js
@@ -274,7 +274,7 @@ class TTLCache {
       if (exp === 'Infinity' || exp > n) {
         return
       }
-      const keys = [...this.expirations[exp]]
+      const keys = [...(this.expirations[exp] || [])]
       const entries = []
       delete this.expirations[exp]
       for (const key of keys) {
```

**Comment by isaacs** [comment]
If you're not doing anything sinful in a disposal method, then my next line of inquiry would be to port the thing to TypeScript and see where it yells at me, which often shakes out hard to see mysteries like this.

**Comment by Tirke** [comment]
@isaacs thanks for the quick update.

We have two of our caches using this as a dispose.

```typescript
      dispose: async (key, value, reason) => {
        this.logger?.debug(`cache dispose - reason: ${reason}`)
        if (reason === 'stale') {
          await this.cache.clear()
        }
      },
```
Is this a potential culprit?

The others are doing this

```typescript
  dispose: async (key, value, reason) => {
    if (reason === 'stale') {
      if (this.loadingCache) {
        return
      }

      this.loadingCache = true
      this.cacheLoaded = false
      try {
        const values = await this.getAllValuesToCache()
        values.forEach((value) =>
          this.cache.set(this.getKeyFromValue(value), value),
        )
        this.cacheLoaded = true
      } catch (error) {
        this.logger?.error(
          `ERR something went wrong while reloading cache: ${
            error instanceof AxiosError ? error.toJSON() : error
          }`,
        )
      }
      this.loadingCache = false
    }
  },
```
