### ISSUE TITLE
Potential issues in CI environment

### ISSUE THREAD

**Issue by erikmellum** [isaacs/ttlcache#29]
After adding this package into our repository we have started seeing non deterministic timeouts in our CI pipeline. I don't have any certainty yet, but is there any known issues with this package causing CI test runs to deadlock in some way? We are running in gitlab CI with node. 

I am opening this for now just to start a discussion. As we investigate this issue I will provide additional information.

**Comment by isaacs** [comment]
Nothing in this library should cause deadlocks. It's unreffing the timers it creates. You might be kicking off some other async action or process that's never resolving?

You can `console.error(process._getActiveHandles(), process._getActiveRequests())` to get some clues about what's keeping the event loop open.
