### ISSUE TITLE
Module not found: Can't resolve 'perf_hooks'

### ISSUE THREAD

**Issue by nguyenyou** [isaacs/ttlcache#8]
I tried to integrate this ttlcache into a Next.js (Typescript) project and receive this error:

> Module not found: Can't resolve 'perf_hooks' in '[...]/node_modules/@isaacs/ttlcache'

## Steps To Reproduce

- Create a fresh Next.js (Typescript) application
```
yarn create next-app my-app --ts
```

- Install `@isaacs/ttlcache` package
 
```
yarn add @isaacs/ttlcache
```

- Open `_app.tsx` and create an instance of TTLCache

```javascript
import "../styles/globals.css";
import type { AppProps } from "next/app";
import TTLCache from "@isaacs/ttlcache";

const cache = new TTLCache({ max: 10, ttl: 1000 });

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

export default MyApp;

```

- Run `yarn dev`, open `http://localhost:3000` and observe

> warn  - ./node_modules/@isaacs/ttlcache/index.js
Module not found: Can't resolve 'perf_hooks' in '[...]/node_modules/@isaacs/ttlcache'

**Comment by nguyenyou** [comment]
I closed this because this issue is Next.js specific issue. Node.js apis can be used in getServerSideProps/getStaticProps as discussed here: https://github.com/vercel/next.js/discussions/12607#discussioncomment-12358

**Comment by nguyenyou** [comment]
Is it ok to make this library works seamlessly on both client-side and server-side, like providing an option for user to choose using only `Date.now()` 🤔

**Comment by MaheshVcsoft** [comment]
I am getting this issue in plain old CRA application as well.
Here are my details:

- node v16.15.1
- "@isaacs/ttlcache": "^1.2.0",
- "react": "^18.2.0"

**Comment by isaacs** [comment]
This should work in environments lacking `perf_hooks` now.

```js
const maybeReqPerfHooks = fallback => {
  try {
    return require('perf_hooks').performance
  } catch (e) {
    return fallback
  }
}
const timeProvider = maybeReqPerfHooks(Date)
const now = () => timeProvider.now()
```

@MaheshVcsoft (or anyone else) if you are encountering this error, something else is going on, please post a new issue with the details of your setup.
